### PR TITLE
feat: add boilerplate for executive report

### PR DESCRIPTION
**Pull request by Toalaah**

### CODE REVIEW

**Comment by EnnioEnnio** [comment]
Could you explain a little what this is needed for? Never used a Dev-shell before :)

**Comment by Toalaah** [comment]
> Could you explain a little what this is needed for?

I am assuming you are only referring to the shell file and not the report-related code, as this is quite self-explanatory I would say? If not: eventually we will need to write the report, and in the spirit of your previous boilerplate commits I thought it might not be a bad idea to already set up a basic build system for this as configuring a new tex project is always a little annoying in my experience, so better get it out of the way now.

> Never used a Dev-shell before :)

A little clarification on this point / why I added it:

Basically, I am using an OS w/out `libc` and other common libraries expected by python modules (well no, I _do_ have `libc`, just not under `/lib`, which breaks pretty much everything when I attempt to install something "normally" (unless it is statically linked or just a simple shell script or something I guess). Hence, I must use this dev-shell to configure my python (and tex, for that matter) environment. Well, I guess with simple deps I wouldn't have to, but since we are using `numpy` and `torch` to name a few, there is no way around this as they both rely quite heavily on c extensions.

To keep it very simple, the file is basically a glorified virtual-env script which can be used by anyone using the `nix` package manager to set up a perfectly reproducible environment down to concrete package/dependency revisions, shell configs, etc, without them having to go out and and manually download + permanently install every single tex, python module on their own. And then when they are done, they leave the directory and their system / dependencies are "reset" to what they were before (like deactivating a virtual-env).

It makes it very effective in reducing the complexity of complex setup instructions, as once you have the shell file dialed in you basically just run one command and then can guarantee that whoever is running your code is doing so with exactly the same versions, dependencies that you are using as well. This is not to say that this project has a complex setup; I only added the file because I quite often work on different systems and otherwise would have to keep on copy-pasting the file around like in the stone-ages :D

I pretty much always use such shell files as I find them quite convenient (even without the aforementioned restrictions which force me to use them). You can probably find some more examples in some of my repos or on GH in general if you are interested, but they are all pretty much the same.

**Comment by EnnioEnnio** [comment]
Yeah, the report was pretty self-explanatory, I should have asked more precisely :D 

Regarding the shell; I get it! 
I just used Conda for setting up my environment and included all packages needed in the `requirements.txt` with instructions on how to install them conveniently with one command in the `README.md`. 
If that doesn't work for you feel free to add the dev shell and merge the two branches :) 

Is it possible for me to still use Conda or would I also have to switch? I'm very used to it atm.

**Comment by Toalaah** [comment]
Yes, I saw the conda installation instructions in the readme; once again, I am not trying to say that the installation instructions are unclear or poorly written, just that they do not work w/ my current setup due to the aforementioned issues. 

Of course these setups are not mutually exclusive, so you are free to use whatever configuration setup you like! In fact, I would probably continue recommending conda, pyenv, etc. in the readme as it is just more common in general.

I would go ahead and merge this now then.

**Pull request merged**
